# Generated by Django 5.2 on 2025-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_billpayment_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
