# Generated by Django 5.2 on 2025-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankaccount_is_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
