# Generated by Django 5.2 on 2025-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15, unique=True),
        ),
    ]
