# Generated by Django 5.2.1 on 2025-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_location_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='marketing_consent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_of_kin_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_of_kin_relationship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin_phone_code',
            field=models.CharField(default='+234', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_code',
            field=models.CharField(default='+234', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
