# Generated by Django 5.2.1 on 2025-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_age_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
